package com.aleksandr.nikitin.pretty_puppies_wallpaper;

public class Wallpapers {

    public static int[] images = {
            R.drawable.img1,
            R.drawable.img2,
            R.drawable.img3,
            R.drawable.img4,
            R.drawable.img5,
            R.drawable.img6,
            R.drawable.img7,
            R.drawable.img8,
            R.drawable.img9,
            R.drawable.img10,
            R.drawable.img11,
            //R.drawable.img12,
            R.drawable.img14,
            R.drawable.img15,
            R.drawable.img16,
            R.drawable.img17,
            R.drawable.img18,
            R.drawable.img21,
            R.drawable.img22,
            R.drawable.img23,
            R.drawable.img24,
            //R.drawable.img25,
            R.drawable.img26,
            R.drawable.img27,
            R.drawable.img28,
            R.drawable.img29,
            R.drawable.img30,
            //R.drawable.img31,
            R.drawable.img32,
            R.drawable.img33,
            R.drawable.img34,
            R.drawable.img35,
            R.drawable.img36,
            R.drawable.img37,
            R.drawable.img38,
            /*
            R.drawable.img39,
            R.drawable.img40,
            R.drawable.img41,
            R.drawable.img42,
            R.drawable.img43,
            R.drawable.img44,
            R.drawable.img45,
            R.drawable.img46,
            R.drawable.img47,
            R.drawable.img48,
            R.drawable.img49,
            R.drawable.img50,
            R.drawable.img51,
            R.drawable.img52,
            R.drawable.img53,
            R.drawable.img54,
            R.drawable.img55,
            R.drawable.img56,
            R.drawable.img57,
            R.drawable.img58,
            R.drawable.img59,
            R.drawable.img60,
            R.drawable.img61,
            R.drawable.img62,
            R.drawable.img63,
            R.drawable.img64,
            R.drawable.img65,
            R.drawable.img66,
            R.drawable.img67,
            R.drawable.img68,
            R.drawable.img69,
            R.drawable.img70,
            R.drawable.img71,
            R.drawable.img72,
            R.drawable.img73,
            R.drawable.img74,
            R.drawable.img75,
            R.drawable.img76,
            */

            R.drawable.imgreward1,
            R.drawable.imgreward2,
            R.drawable.imgreward3

    };

}
